# This is a basic workflow to help you get started with Actions

name: Test

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [main, dev]
  pull_request:
    branches: ["**"]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-20.04]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Compilation
        run: make
      # - name: Setup tmate session
      #   uses: mxschmitt/action-tmate@v3
      - name: Run test
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 10
          command: ./containers
          max_attempts: 5
      - name: Run mli42 test
        run: |
          git clone https://github.com/mli42/containers_test.git && cd containers_test
          perl -i -pe's/#CFLAGS+=" -fsanitize=address -g3"/CFLAGS+=" -fsanitize=address -g3"/' fct.sh
          perl -i -pe's/incl_path="..\/"/incl_path="..\/includes\/"/' fct.sh
          ./do.sh stack vector map
      - name: Generate cov
        run: make cov
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
